bag_config_node:
  bag_def:
    marker_1: [1.1, 2.2, 3.3]
    marker_2: [1.1, 2.2, 3.3]
    marker_3: [1.1, 2.2, 3.3]
    marker_4: [1.1, 2.2, 3.3]
    marker_5: [1.1, 2.2, 3.3]
    marker_6: [1.1, 2.2, 3.3]
    num_markers: 6
  calibrator:
    dropoff:
      marker_0: [1.0, 0.75, -0.9]
      marker_1: [-1.0, 0.75, -0.9]
      marker_2: [0.75, 0.89, 0.92]
      marker_3: [0.75, 0.89, 0.92]
      marker_4: [0.75, 0.89, 0.92]
      marker_5: [0.75, 0.89, 0.92]
      num_markers: 3
    pickup:
      marker_0: [1.0, 0.75, -0.9]
      marker_1: [-1.0, 0.75, -0.9]
      marker_2: [0.75, 0.89, 0.92]
      marker_3: [0.75, 0.89, 0.92]
      marker_4: [0.75, 0.89, 0.92]
      marker_5: [0.75, 0.89, 0.92]
      num_markers: 3
  plot: {calibration: false, estimation: false}
  run_calibration: {dropoff: true, pickup: true}
  sensor_0:
    point: [0, 0, -0.508]
    position: [0.4142, 0.8, 0.4052]
  sensor_1:
    point: [0, 0, -0.508]
    position: [0.4142, -1.1214, 0.4052]
  sensor_2:
    point: [0, 0, -0.508]
    position: [0.75, 0.7242, 0.9479]
  sensor_3:
    point: [0, 0, -0.508]
    position: [0.75, -0.7242, 1.25]
  sensor_4:
    point: [0, 0, -0.508]
    position: [1.0, 0, 1.1934]
  sensor_5:
    point: [2.272, 0.8453, -0.8453]
    position: [1.772, 1.0353, 0.5978]
  sensor_6:
    point: [2.272, 0.8453, -0.8453]
    position: [2.772, 1.0353, 0.5978]
  sensor_7:
    point: [2.272, 0.8453, -0.8453]
    position: [1.272, 0, 1.1955]
  sensor_8:
    point: [2.272, 0.8453, -0.8453]
    position: [3.272, 0, 1.1955]
  sensor_9:
    point: [2.272, 0.8453, -0.8453]
    position: [2.272, -1.0353, 0.5978]
  software_mode: Flight
  thresholds: {covariance: 0.01, time: 30}
rosdistro: 'melodic

  '
roslaunch:
  uris: {host_jabell_thinkpad__36833: 'http://jabell-ThinkPad:36833/', host_jabell_thinkpad__38591: 'http://jabell-ThinkPad:38591/',
    host_jabell_thinkpad__46403: 'http://jabell-ThinkPad:46403/'}
rosversion: '1.14.10

  '
run_id: ac4b26e6-95aa-11eb-9b5a-f85971783868
